resultsdisplay/urls.py
from django.conf.urls import patterns, url
from resultsdisplay import views

urlpatterns = patterns('', 
	url(r'^$', views.IndexView.as_view(), name='index'),

	url(r'^login/$', 'django.contrib.auth.views.login', 
		{'template_name':'resultsdisplay/login.html'}, name='login'),

    url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),

	url(r'^api/(?P<project_name>\w+)/$', views.jsonDump, name='api'),
	url(r'^Project(?P<pk>\d+)/TestRuns/$', views.TestRunView.as_view(), name='TestRun'),
	url(r'^Project(?P<project_pk>\d+)/TestRun(?P<run_num>\d+)_(?P<ordered_run_num>\d+)/PrinterFriendly/$', views.PrinterFriendlyView.as_view(), name='PrinterFriendly'),
	url(r'^Project(?P<project_pk>\d+)/TestRun(?P<run_num>\d+)_(?P<ordered_run_num>\d+)/TestGroups/$', views.TestGroupView.as_view(), name='TestGroup'),
	url(r'^Project(?P<project_pk>\d+)/TestRun(?P<run_num>\d+)_(?P<ordered_run_num>\d+)/TestGroup(?P<group_id>\d+)/TestCases/$', views.TestCaseView.as_view(), name='TestCase'),
	url(r'^Project(?P<project_pk>\d+)/TestRun(?P<run_num>\d+)_(?P<ordered_run_num>\d+)/TestGroup(?P<group_id>\d+)/TestCase(?P<pk>\d+)/Details/$', views.TestResultView.as_view(), name='Details'),
	)

test_results/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('resultsdisplay.urls', namespace="resultsdisplay")),
    #url(r'^admin/', include(admin.site.urls)),
)

resultsdisplay/models.py
from django.db import models
from django.utils import timezone
from  django.contrib.auth.models import AbstractUser
import datetime

class TestCase(models.Model):

    #Should this be an AutoField?
    test_case_id = models.IntegerField(primary_key=True)

    name = models.TextField()
    test_function = models.TextField()
    test_type = models.TextField()
    class Meta:
        managed = False
        db_table = 'test_case'

    def __unicode__(self):
        return self.name


class Project(models.Model):

    #Should this be an AutoField?
    project_id = models.IntegerField(primary_key=True)

    name = models.TextField()
    repo_list = models.TextField()
    class Meta:
        managed = False
        db_table = 'project'

    def __unicode__(self):
        return self.name

class TestResult(models.Model):

    #Should this be an AutoField?
    test_result_id = models.IntegerField(primary_key=True)

    datestamp = models.DateTimeField()
    run_num = models.IntegerField()
    run_time = models.TextField()
    result = models.TextField()
    test_case = models.ForeignKey(TestCase, db_column='test_case_id')
    project = models.ForeignKey(Project, db_column='project_id')
    sha_list = models.TextField()
    xml_path = models.TextField()
    class Meta:
        managed = False
        db_table = 'test_result'

    def __unicode__(self):
        return self.test_result_id

resultsdisplay/views.py
from django.shortcuts import render, render_to_response
from django.views import generic
from django.views.generic.list import MultipleObjectMixin
from django.http import HttpResponse
from resultsdisplay.models import TestResult, TestCase, Project
from django.db.models import Sum, Max
from django.conf import settings
import xml.etree.ElementTree as ET
import requests, base64, json
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django import forms
import re

group_id = {'Unit' : 0, 'Regression' : 1}
group_name = {0 : 'Unit', 1 : 'Regression'}

JENKINS_HOSTNAME = 'jabba'
JENKINS_USERNAME = settings.JENKINS_USERNAME
JENKINS_TOKEN = settings.JENKINS_TOKEN

class RunSelectForm(forms.Form):

	choices = tuple([x['run_num'] for x in TestResult.objects.filter(
				project_id__exact='0').distinct('run_num').values()])
	runs = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple)

class LoginRequiredMixin(object):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)

def jsonDump(request, project_name):

	job_url = 'https://%s/ci/job/%s/'%(JENKINS_HOSTNAME, project_name)
	
	base64string = base64.encodestring('%s:%s' % 
		(JENKINS_USERNAME, JENKINS_TOKEN)).replace('\n','')

	auth_header = {"Authorization":"Basic %s" % base64string}

	job_json = requests.get('%slastBuild/api/json?depth=1' % job_url, 
		verify=False, headers=auth_header).json()

	response_data = {
		'name':project_name,
		'running':(job_json['building'] == True)
	}

	try:
		response_data['progress'] = job_json['executor']['progress']
	except TypeError:
		response_data['progress'] = 0

	return HttpResponse(json.dumps(response_data), content_type="application/json")

class IndexView(LoginRequiredMixin, generic.ListView):

	template_name = 'resultsdisplay/index.html'
	context_object_name = 'project_list'

	def get_queryset(self):
		"""Return all the current projects."""
		return Project.objects.order_by('project_id')

	def get_context_data(self, **kwargs):
		context = super(IndexView, self).get_context_data(**kwargs)

		for aproject in context['project_list']:

			aproject.mostRecentRun = TestResult.objects.filter(project_id__exact=aproject.project_id).aggregate(Max('run_num'))['run_num__max']

			aproject.lastRun = TestResult.objects.filter(
				run_num__exact=aproject.mostRecentRun,
				project_id__exact=aproject.project_id).values()[0]['datestamp']

			aproject.total_time = TestResult.objects.filter(
				run_num__exact=aproject.mostRecentRun,
				project_id__exact=aproject.project_id).aggregate(Sum('run_time'))['run_time__sum']

			aproject.total_tests = TestResult.objects.filter(
				run_num__exact=aproject.mostRecentRun,
				project_id__exact=aproject.project_id).count()

			aproject.total_runs = TestResult.objects.filter(
				project_id__exact=aproject.project_id).distinct('run_num').count()

			aproject.passed = TestResult.objects.filter(
				run_num__exact=aproject.mostRecentRun,
				project_id__exact=aproject.project_id,
				result__exact="PASS").count()

			aproject.failed = TestResult.objects.filter(
				run_num__exact=aproject.mostRecentRun,
				project_id__exact=aproject.project_id,
				result__exact="FAIL").count()

			aproject.errored = TestResult.objects.filter(
				run_num__exact=aproject.mostRecentRun,
				project_id__exact=aproject.project_id,
				result__exact="ERROR").count()

			aproject.total = TestResult.objects.filter(
				run_num__exact=aproject.mostRecentRun,
				project_id__exact=aproject.project_id).count()

		jobs = []

		context['test_running'] = False

		try:

			for project in context['project_list']:

				api_url = 'https://%s/api/%s/' % (JENKINS_HOSTNAME, project.name)

				job_json = requests.get(api_url, verify=False).json()

				a_job = {
					'name':project.name,
					'running': job_json['running'],
					'apiurl':api_url,
				}

				if a_job['running']:
					context['test_running'] = True

					context['err'] = ''

				jobs.append(a_job)

		except Exception as e:
			context['test_running'] = False
			context['err'] = e

		context['job_list'] = jobs

		return context

	def get(self, request, *args, **kwargs):

		self.object_list = self.get_queryset()
		context = self.get_context_data()

		return addCORSHeaders(render(request, self.template_name, context))

class TestRunView(LoginRequiredMixin, generic.ListView):

	pk_url_kwarg = 'run_pk'

	template_name = 'resultsdisplay/TestRun.html'
	context_object_name = 'testrun_list'

	def get_queryset(self):
		return TestResult.objects.filter(project_id__exact=int(self.kwargs['pk'])).values().distinct('run_num')[::-1]

	def get_context_data(self, **kwargs):
		context = super(TestRunView, self).get_context_data(**kwargs)
		context['project_id'] = int(self.kwargs['pk'])
		context['project_name'] = \
			Project.objects.filter(project_id__exact=context['project_id']).values()[0]['name']

		for run in context['testrun_list']:
			var = TestResult.objects.raw('''SELECT sum(CAST (run_time AS float)) AS x
				WHERE run_num = %s''',
				params=[run['run_num']])
			run['total_time'] = TestResult.objects.filter(
				run_num__exact=run['run_num']).aggregate(Sum('run_time'))['run_time__sum']

			run['passed'] = TestResult.objects.filter(
				run_num__exact=run['run_num'],
				result__exact="PASS", 
				project_id__exact=context['project_id']).count()
			run['failed'] = TestResult.objects.filter(
				run_num__exact=run['run_num'],
				project_id__exact=context['project_id'],
				result__exact="FAIL").count()
			run['errored'] = TestResult.objects.filter(
				run_num__exact=run['run_num'],
				project_id__exact=context['project_id'],
				result__exact="ERROR").count()
			run['total'] = TestResult.objects.filter(
				project_id__exact=context['project_id'],
				run_num__exact=run['run_num']).count()

		return context


	def get(self, request, *args, **kwargs):

		self.object_list = self.get_queryset()
		context = self.get_context_data()


		context['POST'] = False
		context['thename'] = 'POST'

		if request.method == 'POST':
			for run in request.POST.getlist('checkbox'):
				TestResult.objects.filter(
					project_id__exact=context['project_id'],
					run_num__exact=run).delete()
			form = RunSelectForm()
			context['POST'] = True
			context['Checkboxes'] = request.POST.getlist('checkbox')

			#Reload objects and context
			self.object_list = self.get_queryset()
			context = self.get_context_data()

		return render(request, self.template_name, context)

	def post(self, request, *args, **kwargs):

		return self.get(request, *args, **kwargs)

class PrinterFriendlyView(LoginRequiredMixin, generic.ListView):

	pk_url_kwarg = 'run_pk'

	template_name = 'resultsdisplay/PrinterFriendly.html'
	context_object_name = 'testresult_list'

	def get_queryset(self):
		"""Return all the current tests for a given run."""
		return TestResult.objects.filter(
			run_num__exact=int(self.kwargs['run_num'])).values()

	def get_context_data(self, **kwargs):
		context = super(PrinterFriendlyView, self).get_context_data(**kwargs)
		context['run_num'] = int(self.kwargs['run_num'])
		context['ordered_run_num'] = int(self.kwargs['ordered_run_num'])
		context['project_id'] = int(self.kwargs['project_pk'])
		context['project_name'] = \
			Project.objects.filter(project_id__exact=context['project_id']).values()[0]['name']
		
		context['total_time'] = TestResult.objects.filter(
			run_num__exact=context['run_num']).aggregate(Sum('run_time'))['run_time__sum']

		context['num_passed'] = TestResult.objects.filter(
			run_num__exact=context['run_num'],
			result__exact="PASS", 
			project_id__exact=context['project_id']).count()
		context['num_failed'] = TestResult.objects.filter(
			run_num__exact=context['run_num'],
			project_id__exact=context['project_id'],
			result__exact="FAIL").count()
		context['num_errored'] = TestResult.objects.filter(
			run_num__exact=context['run_num'],
			project_id__exact=context['project_id'],
			result__exact="ERROR").count()
		context['num_tests'] = TestResult.objects.filter(
			project_id__exact=context['project_id'],
			run_num__exact=context['run_num']).count()

		for run in context['testresult_list']:


			run['name'] = TestCase.objects.filter(test_case_id__exact=run['test_case_id']).values()[0]['name'] 
			
			repo_string = Project.objects.filter(project_id__exact=run['project_id']).values()[0]['repo_list']
			run['repo_list'] = re.findall(r"[\w'\-]+", repo_string)
			run['sha_list'] = re.findall(r"[A-Za-z0-9]+", run['sha_list'])
			run['sha_list'] = [x[:10] for x in run['sha_list']]

			try:
				run['sha_list'] = ["%s: %s" % (run['repo_list'][x], run['sha_list'][x]) for x in range(len(run['sha_list']))]
			except IndexError:
				run['sha_list'] = ['SHAs not available for this run.']

		return context

class TestGroupView(LoginRequiredMixin, generic.ListView):

	pk_url_kwarg = 'run_pk'

	template_name = 'resultsdisplay/TestGroup.html'
	context_object_name = 'testgroup_list'

	def get_queryset(self):
		"""Return all the current test groups."""
		return TestCase.objects.values().distinct('test_type')

	def get_context_data(self, **kwargs):
		context = super(TestGroupView, self).get_context_data(**kwargs)
		context['run_num'] = int(self.kwargs['run_num'])
		context['ordered_run_num'] = int(self.kwargs['ordered_run_num'])
		context['project_id'] = int(self.kwargs['project_pk'])
		context['project_name'] = \
			Project.objects.filter(project_id__exact=context['project_id']).values()[0]['name']

		for group in context['testgroup_list']:

			group['type_num'] = group_id[group['test_type']]


			type_id = {}
			for case in TestCase.objects.values():
				type_id[case['test_case_id']] = case['test_type']

			this_type_name = group['test_type']
			this_type_id = group_id[this_type_name]

			valid_ids = [x for x in type_id if type_id[x] == this_type_name]

			group['total_time'] = TestResult.objects.filter(

resultsdisplay/templates/resultsdisplay/PrinterFriendly.html
{% load split %}
{% load bootstrap3 %}
{% bootstrap_css %}
<div class="container">
<h1>
<img style="height:50px;display:inline" class="img-responsive" src="{{STATIC_URL}}arsenl.bmp"/> ARSENL
</h1>

<table>
<tbody>
<tr> <td> <h3><b>Project: &nbsp;</b></h3></td><td> <h3><font color="#555555">{{project_name}}</font> </h3></td></tr>
<tr> <td> <b> <font color="#317EAC"> Jenkins Run ID: &nbsp; </font> </b></td><td>{{run_num}}</td></tr>
<tr> <td> <b> <font color="#317EAC"> Run Number: &nbsp; </font> </b></td><td> {{ordered_run_num}}</td></tr>
<tr> <td> <b> <font color="#317EAC"> Run on: &nbsp; </font> </b></td><td> {{testresult_list.0.datestamp}}</td></tr>
<tr> <td> <b> <font color="#317EAC"> Time: &nbsp; </font> </b></td><td> {{total_time}} seconds</td></tr>
<tr> <td> <b> <font color="#317EAC"> Tests Run: &nbsp; </font> </td><td> {{num_tests}}, Passed: {{num_passed}}, Failed: {{num_failed}}, Errored: {{num_errored}}</td></tr>
<tr> <td> <b> <font color="#317EAC"> SHAs: &nbsp;</font></b></td><td>

{% for sha in testresult_list.0.sha_list %}

	<br>{{sha}}

{% endfor %}</td></tr>

</table>

<table class="table table-striped" style="border-spacing:10px;">
<thead>
	<tr>
	<td><b><font color="#317EAC">Name</font></b></td>
	<td><b><font color="#317EAC">Result</font></b></td>
	<td><b><font color="#317EAC">Time</font></b></td>
	</tr>
</thead>
{% for test in testresult_list %}
<tbody>
	<tr>
	<td>{{test.name}}</td>
	<td>
		{% if test.result == 'PASS' %}
		<font color="green">
		{% elif test.result == 'ERROR' %}
		<font color="yellow">
		{% else %}
		<font color="red">
		{% endif %}
		&nbsp;&nbsp;{{test.result}} </font>
	</td>
	<td>&nbsp;&nbsp;{{test.run_time}} seconds</td>
	</tr>
</tbody>

{% endfor %}
<table>
</table>

resultsdisplay/templates/resultsdisplay/TestCase.html
{% extends "base.html" %}


{% block breadcrumb %}
<li><a href = "{% url 'resultsdisplay:index' %}"> {{project_name}}</a></li>
<li><a href = "{% url 'resultsdisplay:TestRun' project_id %}"> Run {{ordered_run_num}}</a></li>
<li><a href = "{% url 'resultsdisplay:TestGroup' project_id run_num ordered_run_num %}"> {{type_name}} Tests</a></li>
<li class="active">Test Cases</li>
{% endblock breadcrumb %}

<div class="container">

{% if testcase_list %}
    
	{% block table_toprow %}
        <th> Datestamp </th>
    	<th> Test Name </th>
    	<th> Test Function </th>
    	<th> Result </th>
    	<th> Time </th>
    {% endblock table_toprow %}

    {% block table_contents %}
    {% for testcase in testcase_list %}
    	<tr class="clickableRow" data-url="{% url 'resultsdisplay:Details' testcase.project_id testcase.run_num ordered_run_num group_id testcase.test_result_id %}">
            <td> {{testcase.datestamp|date:"H"}}:{{testcase.datestamp|date:"i"}}:{{testcase.datestamp|date:"s"}}.{{testcase.datestamp|date:"u"|slice:"3"}} </td>
        	<td> {{testcase.name}} </td>
        	<td> {{testcase.test_function}} </td>
        	<td> 
				{%if testcase.result == "PASS"%}
				<font color="green">{{ testcase.result }}</font>
				{%elif testcase.result == "ERROR"%}
				<font color="#b6b600">{{ testcase.result }}</font>
				{%else%}
				<font color="red">{{ testcase.result }}</font>
				{% endif %}
			</td>
        	<td> {{testcase.run_time}} </td>
        </tr>
    {% endfor %}
    {% endblock table_contents %}

{% else %}
    <p>No test cases are available.</p>
{% endif %}
</ul>
</div>

resultsdisplay/templates/resultsdisplay/TestGroup.html
{% extends "base.html" %}

{% block breadcrumb %}
<li><a href = "{% url 'resultsdisplay:index' %}"> {{project_name}}</a></li>
<li><a href = "{% url 'resultsdisplay:TestRun' project_id %}"> Run {{ordered_run_num}}</a></li>
<li class="active">Test Groups</li>
{% endblock breadcrumb %}

<div class="container">

{% if testgroup_list %}
    {% block table_toprow %}
    	<th> Test Group </th>
    	<th> Time </th>
    	<th> PASS </th>
    	<th> FAIL </th>
    	<th> ERROR </th>
    	<th> Total </th>
    {% endblock table_toprow %}

    {% block table_contents %}
    {% for testgroup in testgroup_list %}
    	<tr class="clickableRow" data-url="{% url 'resultsdisplay:TestCase' project_id run_num ordered_run_num testgroup.type_num %}">
    		<td> {{ testgroup.test_type }} </td>
        	<td> {{testgroup.total_time}} </td>
        	<td> {{testgroup.passed}} </td>
        	<td> {{testgroup.failed}} </td>
        	<td> {{testgroup.errored}} </td>
        	<td> {{testgroup.total}} </td>
        </tr>
    {% endfor %}
    {% endblock table_contents %}

{% else %}
    <p>No test groups are available.</p>
{% endif %}
</thead>

resultsdisplay/templates/resultsdisplay/TestResult.html
{% extends "base.html" %}

{% block includes %}
<script type="text/javascript" src="{{ STATIC_URL }}transition.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}collapse.js"></script>
{% endblock includes %}

{% block breadcrumb %}
<li><a href = "{% url 'resultsdisplay:index' %}"> {{project_name}}</a> </li>
<li><a href = "{% url 'resultsdisplay:TestRun' project_id %}"> Run {{ordered_run_num}}</a></li>
<li><a href = "{% url 'resultsdisplay:TestGroup' project_id run_num ordered_run_num %}"> {{type_name}} Tests </a></li>
<li><a href = "{% url 'resultsdisplay:TestCase' project_id run_num ordered_run_num group_id %}"> {{testresult.name}} </a></li>
<li class="active"> Test Details </li>
{% endblock breadcrumb %}

{% block content %}
{% if testresult %}
<table>
<tr><td><strong><font color="#317EAC">Name:</font></strong> &nbsp;&nbsp;</td><td>{{ testresult.name }}</td></tr>
<tr><td><strong><font color="#317EAC">Run Number: </font></strong> &nbsp;&nbsp;</td><td>{{ordered_run_num}} </td></tr>
<tr><td><strong><font color="#317EAC">Jenkins Run: </font></strong> &nbsp;&nbsp;</td><td>{{testresult.run_num}}</td></tr>

<tr><td><strong><font color="#317EAC">Status:</font></strong></td><td>

	{%if testresult.result == "PASS"%}
		<font color="green">
	{%elif testresult.result == "ERROR"%}
		<font color="#b6b600">
	{%else%}
		<font color="red">
	{% endif %}

	{{ testresult.result }}</font>
</td></tr>

<tr><td><strong><font color="#317EAC">Runtime:</font></strong> &nbsp;&nbsp;</td><td>{{ testresult.run_time }}</td></tr>
<tr><td><strong><font color="#317EAC">Datestamp:</font></strong> &nbsp;&nbsp;</td><td>{{ testresult.datestamp }}</td></tr>
<tr><td><strong><font color="#317EAC">SHA List: </font></strong> &nbsp;&nbsp;</td><td>
	<table>
	{% for sha in testresult.sha_list %}
	<tr><td>{{sha}}</td></tr>
	{% endfor %}
	</table>
</td></tr>
<tr><td><strong><font color="#317EAC">Raw XML Output:</font></strong>&nbsp;&nbsp;</td><td><a href="{{ xml_url }}">{{xml_url}}</a></td></tr>
</table>

<div class="panel-group" id="accordion">
	<div class="panel panel-default">
		<div class="panel-heading" data-toggle="collapse">
			<h3 class="panel-title">
			<a data-toggle="collapse" href="#collapseOne"><span class="glyphicon glyphicon-plus"></span>
			<font color="#317EAC"><b>Sys Output</b></font></a></h3>
		</div>

		<div id="collapseOne" class="panel-collapse collapse">
			<div class="panel-body">
				<pre>{{sysout}}</pre>
			</div>
		</div>
	</div>

	<div class="panel panel-default">
		<div class="panel-heading" data-toggle="collapse">
			<h3 class="panel-title">
			<a data-toggle="collapse" href="#collapseTwo"><span class="glyphicon glyphicon-plus"></span>
			<font color="#317EAC"><b>Mav Output</b></font></a></h3>
		</div>

		<div id="collapseTwo" class="panel-collapse collapse">
			<div class="panel-body">
				<pre>{{mavout}}</pre>
			</div>
		</div>
	</div>

	<div class="panel panel-default">
		<div class="panel-heading" data-toggle="collapse">
			<h3 class="panel-title">
			<a data-toggle="collapse" href="#collapseThree"><span class="glyphicon glyphicon-plus"></span>
			<font color="#317EAC"><b>JSBSim Output</b></font></a></h3>
		</div>

		<div id="collapseThree" class="panel-collapse collapse">
			<div class="panel-body">
				<pre>{{jsbout}}</pre>
			</div>
		</div>
	</div>
</div>

 
{% else %}
    <p>No test result details are available.</p>
{% endif %}
{% endblock content %}

resultsdisplay/templates/resultsdisplay/TestRun.html
{% extends "base.html" %}
{% load subtraction %}

{%block includes%}
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
{%endblock includes%}

{% block breadcrumb %}
<li><a href = "{% url 'resultsdisplay:index' %}"> {{ project_name }}</a></li>
<li class="active">Test Runs</li>
{% endblock breadcrumb %}

{% if testrun_list %}

	{% block table_header %}
    	<form name="run_select" action="." method="POST">
    	{% csrf_token %}
	{% endblock table_header %}

	{% block table_toprow %}
		<th> &nbsp; </th>
    	<th id="runheader"> Run </th>
    	<th> Jenkins Run ID </th>
    	<th> Date </th>
    	<th> Time </th>
    	<th> PASS </th>
    	<th> FAIL </th>
    	<th> ERROR </th>
    	<th> Total </th>
    	<th style="text-align:center;"> Changed </th>
    	<th> &nbsp; </th>
    {% endblock table_toprow %}

    {% block table_contents %}
	    {% for testrun in testrun_list reversed %}
	    {% with ordered_run_num=forloop.counter %}

	        <tr class="clickableRow" data-url="{% url 'resultsdisplay:TestGroup' testrun.project_id testrun.run_num ordered_run_num %}">
	        	<td class="unClickable"> <input type="checkbox" name="checkbox" id="checkbox[]" value="{{testrun.run_num}}" /> </td>
	        	<td> {{ordered_run_num}} </td>
	        	<td> {{testrun.run_num }}</td>
	        	<td> {{testrun.datestamp }} </td>
	        	<td> {{testrun.total_time}} </td>
	        	<td> {{testrun.passed}} </td>
	        	<td> {{testrun.failed}} </td>
	        	<td> {{testrun.errored}} </td>
	        	<td> {{testrun.total}} </td>
	        	<td style="text-align:center;color:blue;">  {% ifchanged testrun.sha_list %} <span class="glyphicon glyphicon-record" /> {% endifchanged %} </td>
	        	<td class="unClickable"> <a href="{% url 'resultsdisplay:PrinterFriendly' testrun.project_id testrun.run_num ordered_run_num%}"><span class="glyphicon glyphicon-print" /></a></td>
	        </tr>
	    {% endwith %}

	    {% endfor %}
    {% endblock table_contents %}

    {% block table_footer %}
	<input type="submit" onclick="return confirm('Are you sure you want to delete these?')" value="Delete selected" />
    </form>
    {% endblock table_footer %}

{% block content %}
<script language="javascript" type="text/javascript">
window.onload = function(){
	$("#runheader").trigger("click");
	$("#runheader").trigger("click");
};
</script>
{% endblock content %}

{% else %}
    <p>No test runs are available.</p>
{% endif %}

resultsdisplay/templates/resultsdisplay/login.html
{% extends "base.html" %}



{% block content %}
{{form.errorsjdrus}}
<div class="container" align="center">
<div class="well" style="width:500px;" align="left">

<form action="{% url 'resultsdisplay:login' %}" method="post">
    <div class="form-group">
        <label for="inputUsename">Username</label>
        <input type="username" class="form-control" id="username"
        placeholder="Username" name="username">
    </div>
    <div class="form-group">
        <label for="inputPassword">Password</label>
        <input type="password" class="form-control" id="password"
        placeholder="Password" name="password">
    </div>
    {% csrf_token %}
    <input type="hidden" name="next" value="{% url 'resultsdisplay:index' %}" /> 
    <input type="submit" id="submit" value="Login" class="btn btn-primary" />
</form>

</div>
</div>

{% endblock content %}

<!-- <html>
<body>
    {%if form.errors %}
    <p> Invalid username/password combination, please try again </p>
    {% endif %}

    <h1>Welcome to My Site!</h1>
    <form action="{% url 'resultsdisplay:login' %}" method="post">
    {% csrf_token %}
        {{form.username.label_tag}}{{form.username}}
        {{form.password.label_tag}}{{form.password}}
        <input type="submit" id="submit" name="submit" value="Sign in" />
        <input type="hidden" name="next" value="{% url 'resultsdisplay:index' %}" />        
    </form>
</body>
</html> -->